version: '3'
services:
  phoenix:
    build: .
    ports:
        - "4000:4000"
    volumes:
        - home:/home/phoe
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
    home:
